# Author:cenzhongman
# E-mail:cenzhongman@163.com

version: '3.1'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3306:3306
    volumes: 
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD

volumes: 
  mysql: